# -*- coding: utf-8 -*-
"""24B1019_WEEK_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWJdyncKtJ6QFDNGTy3ln1iKGPTdtADU

# micrograd exercises

1. watch the [micrograd video](https://www.youtube.com/watch?v=VMj-3S1tku0) on YouTube
2. come back and complete these exercises to level up :)

## section 1: derivatives
"""

# here is a mathematical expression that takes 3 inputs and produces one output
from math import sin, cos

def f(a, b, c):
  return -a**3 + sin(3*b) - 1.0/c + b**2.5 - a**0.5

print(f(2, 3, 4))

""" IN THIS CELL, I JUST ADDED CONTENT IN *gradf* FUNCTION SO AS TO FIND THE GRADIENT

"""

# write the function df that returns the analytical gradient of f
# i.e. use your skills from calculus to take the derivative, then implement the formula
# if you do not calculus then feel free to ask wolframalpha, e.g.:
# https://www.wolframalpha.com/input?i=d%2Fda%28sin%283*a%29%29%29

from math import sin,cos
def gradf(a, b, c):
  df_da = -3*a**2 -0.5*a**(-0.5)
  df_db = 3*cos(3*b) +2.5*b**1.5
  df_dc = 1.0/(c**2)
  return [df_da,df_db,df_dc] # todo, return [df/da, df/db, df/dc]

# expected answer is the list of
ans = [-12.353553390593273, 10.25699027111255, 0.0625]
yours = gradf(2, 3, 4)
for dim in range(3):
  ok = 'OK' if abs(yours[dim] - ans[dim]) < 1e-5 else 'WRONG!'
  print(f"{ok} for dim {dim}: expected {ans[dim]}, yours returns {yours[dim]}")

"""IN THIS CELL, I CREATED *grad_f* FUNCTION TO FIND THE GRADIENT NUMERICALLY"""

# now estimate the gradient numerically without any calculus, using
# the approximation we used in the video.
# you should not call the function df from the last cell

def grad_f(a,b,c):
  h=0.000001
  fa = f(a,b,c)
  f1 = f(a+h,b,c)
  df_da = (f1-fa)/h
  f2 = f(a,b+h,c)
  df_db = (f2-fa)/h
  f3 = f(a,b,c+h)
  df_dc = (f3-fa)/h
  return [df_da,df_db,df_dc]
# -----------
numerical_grad = grad_f(2,3,4) # TODO
# -----------

for dim in range(3):
  ok = 'OK' if abs(numerical_grad[dim] - ans[dim]) < 1e-5 else 'WRONG!'
  print(f"{ok} for dim {dim}: expected {ans[dim]}, yours returns {numerical_grad[dim]}")

"""IN THIS CELL, I CREATED *new_gradf* FUNCTION TO FIND GRADIENT USING SYMMETRIC DERIVATIVE METHOD"""

# there is an alternative formula that provides a much better numerical
# approximation to the derivative of a function.
# learn about it here: https://en.wikipedia.org/wiki/Symmetric_derivative
# implement it. confirm that for the same step size h this version gives a
# better approximation.

def new_gradf(a,b,c):
  h=0.000001
  my_ans=[]
  for i in range(3):
    var=[a,b,c]
    var[i]+=h
    f1=f(var[0],var[1],var[2])
    var[i]-=(2*h)
    f2=f(var[0],var[1],var[2])
    df=(f1-f2)/(2*h)
    my_ans.append(df)
  return my_ans
# -----------
numerical_grad2 = new_gradf(2,3,4) # TODO
# -----------

for dim in range(3):
  ok = 'OK' if abs(numerical_grad2[dim] - ans[dim]) < 1e-5 else 'WRONG!'
  print(f"{ok} for dim {dim}: expected {ans[dim]}, yours returns {numerical_grad2[dim]}")

"""## section 2: support for softmax

IN THIS CELL, I JUST ADDED THE NECESSARY FUNCTIONS IN THE TODO PLACE
"""

# Value class starter code, with many functions taken out
from math import exp, log

class Value:

  def __init__(self, data, _children=(), _op='', label=''):
    self.data = data
    self.grad = 0.0
    self._backward = lambda: None
    self._prev = set(_children)
    self._op = _op
    self.label = label

  def __repr__(self):
    return f"Value(data={self.data})"

  def __add__(self, other): # exactly as in the video
    other = other if isinstance(other, Value) else Value(other)
    out = Value(self.data + other.data, (self, other), '+')

    def _backward():
      self.grad += 1.0 * out.grad
      other.grad += 1.0 * out.grad
    out._backward = _backward

    return out

  # ------
  def __radd__(self,other):
     return self + other

  def exp(self):
    out = Value(exp(self.data),(self,),'exp')

    def _backward():
      self.grad += out.data*out.grad
    out._backward = _backward

    return out

  def __truediv__(self,other):
    other = other if isinstance(other, Value) else Value(other)
    return self * other**-1

  def __pow__(self,other):
    out = Value(self.data**other,(self,))

    def _backward():
      self.grad += other*(self.data**(other-1))*out.grad

    out._backward=_backward
    return out

  def __mul__(self,other):
    other=other if isinstance(other,Value) else Value(other)
    x=Value((self.data)*(other.data),(self,other),'*')

    def  _backward():
      self.grad += (other.data)*x.grad
      other.grad += (self.data)*x.grad

    x._backward=_backward
    return x

  def log(self):
    out = Value(log(self.data),(self,))

    def _backward():
      self.grad += out.grad/self.data

    out._backward = _backward
    return out

  def __neg__(self):
    return self * -1
  # ------

  def backward(self): # exactly as in video
    topo = []
    visited = set()
    def build_topo(v):
      if v not in visited:
        visited.add(v)
        for child in v._prev:
          build_topo(child)
        topo.append(v)
    build_topo(self)

    self.grad = 1.0
    for node in reversed(topo):
      node._backward()

# without referencing our code/video __too__ much, make this cell work
# you'll have to implement (in some cases re-implemented) a number of functions
# of the Value object, similar to what we've seen in the video.
# instead of the squared error loss this implements the negative log likelihood
# loss, which is very often used in classification.

# this is the softmax function
# https://en.wikipedia.org/wiki/Softmax_function
def softmax(logits):
  counts = [logit.exp() for logit in logits]
  denominator = sum(counts)
  out = [c / denominator for c in counts]
  return out

# this is the negative log likelihood loss function, pervasive in classification
logits = [Value(0.0), Value(3.0), Value(-2.0), Value(1.0)]
probs = softmax(logits)
loss = -probs[3].log() # dim 3 acts as the label for this input example
loss.backward()
print(loss.data)

ans = [0.041772570515350445, 0.8390245074625319, 0.005653302662216329, -0.8864503806400986]
for dim in range(4):
  ok = 'OK' if abs(logits[dim].grad - ans[dim]) < 1e-5 else 'WRONG!'
  print(f"{ok} for dim {dim}: expected {ans[dim]}, yours returns {logits[dim].grad}")

"""HERE, I JUST WROTE THE VERIFICATION PART USING PYTORCH AND VERIFIED IT"""

# verify the gradient using the torch library
# torch should give you the exact same gradient
import torch

def softmax(logits):
  counts = torch.exp(logits)
  out = counts/counts.sum()
  return out

logits = torch.tensor([0.0,3.0,-2.0,1.0],requires_grad=True)
probs = softmax(logits)
loss = -torch.log(probs[3])
loss.backward()
print(loss.item())

ans = [0.041772570515350445, 0.8390245074625319, 0.005653302662216329, -0.8864503806400986]
for dim in range(4):
  ok = 'OK' if abs(logits.grad[dim].item() - ans[dim]) < 1e-5 else 'WRONG!'
  print(f"{ok} for dim {dim}: expected {ans[dim]}, yours returns {logits.grad[dim].item()}")